.TH ARCO-SVG2PDF 1 "September 2026" "arco-authors" "ARCO authors tools"
.SH NAME
arco-svg2pdf \- convert an SVG file to PDF with Inkscape
.SH SYNOPSIS
.B arco-svg2pdf
.I svg-file
.I pdf-file
.SH DESCRIPTION
.B arco-svg2pdf
converts
.I svg-file
to
.I pdf-file
using
.BR inkscape (1).
It works with Inkscape versions before and after 1.0.
.SH SEE ALSO
.BR arco-svg2png (1),
.BR inkscape (1)
